version: "3.8"
services: 
  #reverse-proxy:
  #  image: traefik:v2.2
  #  command:
  #    - "--api.insecure=true"
  #    - "--providers.docker"
  #    - "--providers.docker.exposedByDefault=false"
  #  ports:
  #    - "80:80"
  #    - "8080:8080"
  #  volumes: 
  #    - /var/run/docker.sock:/var/run/docker.sock
  service-db:
    image: "mysql:8"
    container_name: service-db
    ports:
      - 3306:3306
    volumes:
    - ./initdb.d:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_DATABASE=crypto-db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  redis-account:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"
  back-server:
    build:
      context: ./back-server
      target: builder
    image: back-server
    env_file: ./back-server/.env.dev
    ports:
      - "8080:8080"
    environment: 
      - ENV=dev
    volumes: 
      - ./back-server:/go/src/app
    depends_on:
      - redis-account
      - service-db
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"
volumes:
  redisdata:
  